Revert "Fix incompatible class change error for JIT stress mode"
This reverts commit 0e430fac43f36689cefa923d0a6b4cce76206b73.

Fixes KakaoTalk app crash.

Crash logs:

Build fingerprint: 'samsung/jaltektt/jaltektt:5.0.1/LRX22C/E300KKTUGOL5:user/release-keys'
Revision: '10'
ABI: 'arm'
pid: 14496, tid: 14496, name: com.kakao.talk  >>> com.kakao.talk <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
    r0 beb99350  r1 beb990c0  r2 00000001  r3 00000000
...
backtrace:
    #00 pc 00164c5a  /system/lib/libart.so (bool art::interpreter::DoFieldPut<(art::FindFieldType)1, (art::Primitive::Type)0, true, false>(art::Thread*, art::ShadowFrame const&, art::Instruction const*, unsigned short)+585)
    #01 pc 000a045b  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<true, false>(art::Thread*, art::MethodHelper&, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+24290)
    #02 pc 0015fe2d  /system/lib/libart.so (art::interpreter::EnterInterpreterFromStub(art::Thread*, art::MethodHelper&, art::DexFile::CodeItem const*, art::ShadowFrame&)+180)
    #03 pc 002860e7  /system/lib/libart.so (artQuickToInterpreterBridge+482)
    #04 pc 000a8d9b  /system/lib/libart.so (art_quick_to_interpreter_bridge+10)
    #05 pc 004ea7dc  /dev/ashmem/dalvik-main space (deleted)
...

E/NativeCrashHandler(16201): Crash In Native Code! [pid: 16201 | tid 16201]
F/art     (16201): art/runtime/thread.cc:1108] No pending exception expected: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/animation/BaseInterpolator;
...
F/art     (16201): art/runtime/thread.cc:1108] Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.animation.BaseInterpolator" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.kakao.talk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kakao.talk-1/lib/arm, /vendor/lib, /system/lib]]
F/art     (16201): art/runtime/thread.cc:1108]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
...